### PR TITLE
Create necropolis

### PR DESCRIPTION
**Pull request by Shdorsh**
An improved and reviewed version of my old script from yesterday, tested on my private server. Hope you guys will find it to your liking. I'm still improving in modding SS13.

[Changelogs]: # Just added a new spell named conjure tendril, which casts a necropolis tendril that doesn't cause any chasms to appear.

:cl: New wiznerd spell

add: New spell: Conjure tendril /obj/effect/proc_holder/spell/aoe_turf/conjure/necropolis
/:cl:

[why]: # My first attempts at modding the game and the first thing I thought would add some variety to gameplay. Maybe

### CODE REVIEW

**Comment by mlgdatboi** [comment]
No

**Comment by mlgdatboi** [comment]
to op ):

**Comment by Shdorsh** [comment]
Well, it is kinda like the bee spell, only with less cost but higher cooldown and different mobs. Especially the no chasms part should make it less extreme.

**Comment by mlgdatboi** [comment]
It spawns NPC's thats not really "less extreme"

**Comment by Shdorsh** [comment]
Worse can be done with bees, especially since the cooldown is MUCH lower and it spawns more mobs. So if you want to flood with mobs, use that instead. Just try it out first before complaining.

**Pull request closed without merging**
